.\" SPDX-License-Identifier: BSD-2-Clause
.\" Copyright (C) 2018 - 2019 Intel Corporation.
.\"
.TH "MEMKIND-HBW_NODES" 1 "2018-03-12" "Intel Corporation" "MEMKIND-HBW_NODES" \" -*- nroff -*-
.SH "NAME"
memkind-hbw-nodes - print comma-separated list of high bandwidth nodes.
.br
Note: This is EXPERIMENTAL API. The functionality and the header file itself can be changed (including non-backward compatible changes), or removed.
.SH "SYNOPSIS"
memkind-hbw-nodes [-h|--help]
.SH "DESCRIPTION"
.BR memkind-hbw-nodes
prints a comma-separated list of high bandwidth NUMA nodes that can be used with the numactl --membind option.
.SH "OPTIONS"
.BR " -h, --help"
              Displays help text and exit.
.SH "EXIT STATUS"
.BR memkind-hbw-nodes
exits with status 0 on success, 1 on failure, 2 on invalid argument.
.SH "COPYRIGHT"
Copyright (C) 2016 - 2019 Intel Corporation. All rights reserved.
.SH "SEE ALSO"
.BR hbwmalloc (3),
.BR memkind (3),
.BR numactl (8)
.SH "AUTHOR"
Krzysztof Kulakowski <krzysztof.kulakowski@intel.com>
