.\" SPDX-License-Identifier: BSD-2-Clause
.\" Copyright (C) 2019 - 2020 Intel Corporation.
.\"
.TH "MEMKIND-AUTO-DAX-KMEM-NODES" 1 "2019-08-29" "Intel Corporation" "MEMKIND-AUTO-DAX-KMEM-NODES" \" -*- nroff -*-
.SH "NAME"
memkind-auto-dax-kmem-nodes - prints comma-separated list of automatically detected persistent memory NUMA nodes.
.br
Note: This is EXPERIMENTAL API. The functionality and the header file itself can be changed (including non-backward compatible changes), or removed.
.SH "SYNOPSIS"
memkind-auto-dax-kmem-nodes [-h|--help]
.SH "DESCRIPTION"
.BR memkind-auto-dax-kmem-nodes
prints a comma-separated list of automatically detected persistent memory NUMA nodes that can be used with the numactl --membind option.
.SH "OPTIONS"
.BR " -h, --help"
              Displays help text and exit.
.SH "EXIT STATUS"
.BR 0
on success
.br
.BR 1
if automatic detection is disabled (memkind wasn't build with suitable libdaxctl-devel version)
.br
.BR 2
if argument is invalid
.br
.BR 3
on other failure
.SH "COPYRIGHT"
Copyright (C) 2019 - 2020 Intel Corporation. All rights reserved.
.SH "SEE ALSO"
.BR daxctl (3),
.BR memkind (3),
.BR numactl (8)
.SH "AUTHOR"
Michal Biesek <michal.biesek@intel.com>
