.\" SPDX-License-Identifier: BSD-2-Clause
.\" Copyright (C) 2019 - 2020 Intel Corporation.
.\"
.TH "MEMKIND_DAX_KMEM" 3 "2019-07-19" "Intel Corporation" "MEMKIND_DAX_KMEM" \" -*- nroff -*-
.SH "NAME"
memkind_dax_kmem \- DAX KMEM memory memkind operations.
.br
.BR Note:
This is EXPERIMENTAL API. The functionality and the header file itself can be changed (including non-backward compatible changes) or removed.
.SH "SYNOPSIS"
.sp
.BI "int memkind_dax_kmem_all_get_mbind_nodemask(struct memkind " "*kind" ", unsigned long " "*nodemask" ", unsigned long " "maxnode" );
.br
.SH DESCRIPTION
.PP
DAX KMEM memory memkind operations.
.PP
.BR memkind_dax_kmem_all_get_mbind_nodemask ()
sets the
.I nodemask
bits to one that correspond to the all persistent memory NUMA nodes in
the system. All other bits up to
.I maxnode
are set to zero.
The
.I nodemask
can be used in conjunction with the
.BR mbind (2)
system call.
.SH "COPYRIGHT"
Copyright (C) 2019 - 2020 Intel Corporation. All rights reserved.
.SH "SEE ALSO"
.BR memkind (3),
.BR memkind_arena (3),
.BR memkind_default (3),
.BR memkind_hugetlb (3),
.BR memkind_pmem (3),
.BR memkind_hmat (3),
.BR jemalloc (3),
.BR mbind (2),
.BR mmap (2)
