.\" SPDX-License-Identifier: BSD-2-Clause
.\" Copyright (C) 2021 Intel Corporation.
.\"
.TH "MEMTIER" 7 "2021-03-01" "Intel Corporation" "MEMTIER" \" -*- nroff -*-
.SH "NAME"
libmemtier.so \- TODO
.SH "SYNOPSIS"
.BR LD_PRELOAD=libmemtier.so
command {arguments ...}
.SH "DESCRIPTION"
.B TODO

.SH "ENVIRONMENT"
.TP
.B MEMKIND_MEM_TIERING_CONFIG
Sets the memkind tiering functionality. Passed as a comma separated list of
.I memkind_tier
configuration strings ended with a policy. The configuration has to be passed in the following format:
.IP
"kind_name:[path_to_pmem:pmem_file_size:]ratio,(...),policy"
, where:
.IP
.BR
kind_name - the name of a kind used in tiering. Allowed kind names are 'DRAM' and 'FS_DAX'.
.IP
.BR
path_to_pmem - the path to the location where pmem file will be created. The path has to exist. Pass this option
only with FS_DAX kind.
.IP
.BR
pmem_file_size - the size of pmem file, it's the maximum size of total allocations to PMEM. Pass this option
only with FS_DAX kind. The accepted formats are: 1, 1K, 1M, 1G. See
.I memkind(3)
manual for information about limitations to this value which are the same as for the
.I max_size
value in
.I memkind_create_pmem()
function.
.IP
.BR
ratio - the part of ratio tied to the given kind. It's represented as an
.I unsigned
type. Value should be in range from 1 to
.I UINT_MAX
.IP
.BR
policy - determines the algorithm used to distribute allocations between provided memory kinds. Currently only
.I STATIC_THRESHOLD
policy is valid meaning that allocations are made in such a way that the ratio between memory kinds is static.
.IP
See
.I EXAMPLES
section for an example of usage of
.I MEMKIND_MEM_TIERING_CONFIG
environment variable.
.IP
NOTE: The application will fail when provided environment variable string is not in a correct format.

.SH "EXAMPLES"
.br
The following will run /bin/ls with Memtier library. Make sure that paths to
both libmemtier.so and libmemkind.so are included in
.B LD_LIBRARY_PATH.
.IP
.B LD_PRELOAD=libmemtier.so
/bin/ls -l
.PP
Example usage of MEMKIND_MEM_TIERING_CONFIG environment variable where 20% of allocations will go to PMEM
and 80% of allocations will go to DRAM:
.IP
.B MEMKIND_MEM_TIERING_CONFIG="FS_DAX:/tmp/:10G:1,DRAM:4,STATIC_THRESHOLD"

.SH "COPYRIGHT"
Copyright (C) 2021 Intel Corporation. All rights reserved.

.SH "SEE ALSO"
.BR memkind(3),
.BR malloc (3)
