.\" SPDX-License-Identifier: BSD-2-Clause
.\" Copyright (C) 2021 Intel Corporation.
.\"
.TH "MEMTIER" 7 "2021-03-01" "Intel Corporation" "MEMTIER" \" -*- nroff -*-
.SH "NAME"
libmemtier.so \- TODO
.SH "SYNOPSIS"
.BR LD_PRELOAD=libmemtier.so
command {arguments ...}
.SH "DESCRIPTION"
.B TODO

.SH "ENVIRONMENT"

The behavior of Memtier library is controlled by the following environment
variables.

TODO

.SH "EXAMPLES"
.br
The following will run /bin/ls with Memtier library. Make sure that paths to
both libmemtier.so and libmemkind.so are included in
.B LD_LIBRARY_PATH.
.IP
.B LD_PRELOAD=libmemtier.so
/bin/ls -l

.SH "COPYRIGHT"
Copyright (C) 2021 Intel Corporation. All rights reserved.

.SH "SEE ALSO"
.BR memkind(3)
.BR malloc (3)
