arch:
  - amd64
  - ppc64le
ignore:
  - "autohbw/.*"
  - "examples/autohbw*"
  - "examples/*example*"
  - "examples/memkind*"
  - "src/tbb_wrapper.c"
  - "test/.*"
  - "utils/**/*"

coverage:
  range: "60...100"

comment:
  layout: "diff"
  behaviour: default
  require_changes: true
