#!/bin/bash
#
#  Copyright (C) 2014 Intel Corporation.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright notice(s),
#     this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice(s),
#     this list of conditions and the following disclaimer in the documentation
#     and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER(S) ``AS IS'' AND ANY EXPRESS
#  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# This shell script takes care creating and deleting accesible
# bandwidth files from PMTT tables
### BEGIN INIT INFO
# Provides: memkind
# Required-Start:
# Required-Stop:
# Short-Description: Sets up memkind library
# Description: Parses the PMTT table and creates the file /etc/memkind/node-bandwidth.
#
#              start - Create bandwidth file from PMTT table.
#
#              stop  - Delete bandwidth file from /etc/memkind.
#
#              restart - Delete and recreate bandwidth file from PMTT table.
#
#              force-reload - Delete and recreate bandwidth file.  Ignore deletion errors.
#
#              status - Print existance of bandwidth file
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO

if [ -s /etc/rc.status ]; then
    . /etc/rc.status
    echo_success() {
        echo $1
        rc_failed 0
        rc_status -v1
    }
    echo_failure() {
        echo $1
        rc_failed 1
        rc_status -v1
    }
elif [ -s /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
else
    echo_success() {
        echo $1
    }
    echo_failure() {
        echo ERROR: $1
    }
fi

err=0
FILE=/etc/memkind/node-bandwidth
DIR=`dirname $FILE`
MEMKIND_BIN=/usr/sbin/memkind-pmtt

start() {
    echo_success "creating bandwidth values file"
    $MEMKIND_BIN
    err=$?
    if [ $err -eq 0 ] && [ -f $FILE ]
    then
        echo_success "created file: $FILE"
    else
        echo_failure "could not create file: $FILE"
    fi
}

stop() {
    echo_success "deleting bandwidth values file"
    rm $FILE
    err=$?
    if [ $err -eq 0 ] && [ ! -f $FILE ]
    then
        echo_success "deleted file: $FILE"
        rmdir $DIR
        err=$?
        if [ $err -eq 0 ] && [ ! -d $DIR ]
        then
            echo_success "deleted directory: $DIR"
        else
            echo_failure "could not delete directory: $DIR"
        fi
    else
        echo_failure "could not delete file: $FILE"
    fi
}

restart() {
    stop
    if [ $err -eq 0 ]
    then
        start
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    force-reload)
        stop
        start
        ;;
    status)
        if [ -f $FILE ];
        then
            echo_success "file $FILE exists"
            err=0
        else
            echo_failure "file $FILE does not exists"
            err=3
        fi
        ;;
    condrestart|try-restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status|condrestart|try-restart}"
        err=2
esac
exit $err
