#!/bin/bash
#
# This shell script takes care creating and deleting accesible 
# bandwidth files from PMTT tables
### BEGIN INIT INFO
# start - Create bandwidth file from PMTT table
# stop  - Delete bandwidth file from /etc/
# restart - Delete and recreate file from PMTT table
### END INIT INFO
 
err=0
FILE=/etc/numakind/node-bandwidth
 
start() {
    echo "LOG: <$0> creating bandwidth values file: $FILE"
    /usr/sbin/numakind-pmtt
    err=$?
    if [ $err -ne 0 ]
    then
        echo "ERROR: <$0> could not create file: $FILE" 1>&2 
    fi
}
 
stop() {
    echo "LOG: <$0> deleting bandwidth values file: $FILE"
    rm $FILE
    err=$?
    if [ $err -ne 0 ]
    then
        echo "ERROR: <$0> could not delete file: $FILE" 1>&2 
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        if [ $err -eq 0 ]
        then
            start
        fi
        ;;
    status)

        if [ -f $FILE ];
        then
            echo "LOG: <$0> file $FILE exists"
        else
            echo "LOG: <$0> File $FILE does not exists"
        fi
        ;;
esac
 
exit $err