#!/bin/bash
#
# This shell script takes care creating and deleting accesible
# bandwidth files from PMTT tables
### BEGIN INIT INFO
# Provides: numakind
# Short-Description: Sets up numakind library
# Description: Parses the PMTT table and creates the file /etc/numakind/node-bandwidth.
#
#              start - Create bandwidth file from PMTT table.
#
#              stop  - Delete bandwidth file from /etc/numakind.
#
#              restart - Delete and recreate bandwidth file from PMTT table.
#
#              force-reload - Delete and recreate bandwidth file.  Ignore deletion errors.
#
#              status - Print existance of bandwidth file
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO

. /etc/rc.d/init.d/functions

err=0
FILE=/etc/numakind/node-bandwidth

start() {
    echo_success "creating bandwidth values file"
    numakind-pmtt
    err=$?
    if [ ! $err ] && [ -f $FILE ]
    then
        echo_success "created file: $FILE"
    else
        echo_failure "could not create file: $FILE"
    fi
}

stop() {
    echo_success "deleting bandwidth values file"
    rm $FILE
    err=$?
    if [ ! $err ] && [ ! -f $FILE ]
    then
        echo_success "deleted file: $FILE"
    else
        echo_failure "could not delete file: $FILE"
    fi
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        if [ ! $err ]
        then
            start
        fi
        ;;
    force-reload)
        stop
        start
        ;;
    status)

        if [ -f $FILE ];
        then
            echo_success "file $FILE exists"
        else
            echo_success "file $FILE does not exists"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload}"
        err=2
esac
log_end_msg $err
exit $err