# SPDX-License-Identifier: BSD-2-Clause
# Copyright (C) 2019 - 2020 Intel Corporation.

# Pull base image
FROM ubuntu:20.04

LABEL maintainer="katarzyna.wasiuta@intel.com"

# Update the Apt cache and install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    asciidoctor \
    automake \
    bash-completion \
    ca-certificates \
    curl \
    devscripts \
    g++ \
    git \
    libjson-c-dev \
    libkeyutils-dev \
    libkmod-dev \
    libnuma-dev \
    libtool \
    libudev-dev \
    numactl \
    pkg-config \
    python3-pip \
    sudo \
    systemd \
    uuid-dev \
    whois \
 && rm -rf /var/lib/apt/lists/*

# Install packages required by python tests
RUN pip3 install wheel
RUN pip3 install pytest==3.9.2

# Add user
ENV USER memkinduser
ENV USERPASS memkindpass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Create directory for memkind repository
WORKDIR /home/$USER/memkind

# Allow user to create files in the home directory
RUN chown -R $USER:sudo /home/$USER

# Change user to $USER
USER $USER
