# SPDX-License-Identifier: BSD-2-Clause
# Copyright (C) 2019 - 2021 Intel Corporation.

# Pull base image
FROM ubuntu:20.04

LABEL maintainer="michal.biesek@intel.com"

# Set apt-get proxy
RUN echo "Acquire::http::proxy \"$HTTP_PROXY\";\nAcquire::https::proxy \"$HTTPS_PROXY\";" > /etc/apt/apt.conf

# Update the Apt cache and install basic tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    asciidoctor \
    automake \
    bash-completion \
    ca-certificates \
    curl \
    devscripts \
    g++ \
    git \
    libattr1-dev \
    libcap-ng-dev \
    libglib2.0-dev \
    libgnutls28-dev \
    libjson-c-dev \
    libkeyutils-dev \
    libkmod-dev \
    libnuma-dev \
    libpciaccess-dev \
    libpixman-1-dev \
    libtirpc-dev \
    libtool \
    libudev-dev \
    libxml2-dev \
    libxml2-utils \
    numactl \
    ninja-build \
    pkg-config \
    python-docutils \
    python3-pip \
    python3.8-dev \
    sudo \
    systemd \
    uuid-dev \
    xsltproc \
    whois \
 && rm -rf /var/lib/apt/lists/*

# Install packages required by python tests
RUN pip3 install wheel
RUN pip3 install pytest==3.9.2
RUN pip3 install fabric
RUN pip3 install psutil
RUN pip3 install meson

# Add user
ENV USER memkinduser
ENV USERPASS memkindpass
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Create directory for memkind repository
WORKDIR /home/$USER/memkind

# Allow user to create files in the home directory
RUN chown -R $USER:sudo /home/$USER

# Change user to $USER
USER $USER
