
perf_tool: main.cpp ScenarioWorkload.cpp FootprintTask.cpp FunctionCallsPerformanceTask.cpp FootprintSampling.cpp
	g++ -o perf_tool main.cpp ScenarioWorkload.cpp FootprintTask.cpp FunctionCallsPerformanceTask.cpp FootprintSampling.cpp -O0 -lmemkind -std=c++11 -lpthread
