#!/usr/bin/env python

import sys
import re
import itertools

class License(object):
    def __init__(self, lic_text):
        base_filter = r'[ \t\r\f\v]*[!@#$*/%;]*[ \t\r\f\v]*'
        self.sleft_filter = re.compile(r'\A' + base_filter)
        self.left_filter = re.compile(r'\n' + base_filter)
        self.right_filter = re.compile(base_filter + r'\n')
        self.eright_filter = re.compile(base_filter + r'\Z')
        self.search_length = 1024
        assert(self.search_length > 4*len(lic_text.splitlines()))
        self.lic = self._filter(lic_text)
        assert(len(self.lic) != 0)

    def check(self, path):
        with open(path) as fid:
            head = list(itertools.islice(fid, self.search_length))
        head = ''.join(head)
        head = self._filter(head)
        if self.lic in head:
            return 0
        return -2

    def _filter(self, string):
        result = self.sleft_filter.sub('', string)
        result = self.left_filter.sub('\n', result)
        result = self.right_filter.sub('\n', result)
        result = self.eright_filter.sub('', result)
        return result

if __name__ == '__main__':
    lic = open(sys.argv[1]).read()
    path = sys.argv[2]
    lic = License(lic)
    sys.exit(lic.check(path))
